http:
  port: "8081"
  
sfdc:
  username: "raviteja@njclabs.com"
  password: "Madishetty@27"
  token: "7X69g02WfpZxCtXQL59HROGBF"
  
file:
  accountsDir: "C:/Users/madis/Downloads/MUFundamentals4.3_studentFiles_12may2020/MUFundamentals4.3_studentFiles_12may2020/resources"

db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"